import { Transaction, LoadModelConfig } from '../types';

/**
 * Base interface for all tool adapters
 */
export interface IToolAdapter {
  readonly toolName: string;
  readonly fileExtension: string;

  /**
   * Generate script from transactions
   */
  generate(transactions: Transaction[], loadConfig: LoadModelConfig): string;

  /**
   * Generate script and save to file
   */
  generateAndSave(
    transactions: Transaction[],
    loadConfig: LoadModelConfig,
    filePath: string
  ): Promise<void>;
}

/**
 * Base adapter class with common functionality
 */
export abstract class BaseToolAdapter implements IToolAdapter {
  abstract readonly toolName: string;
  abstract readonly fileExtension: string;

  /**
   * Generate script content
   */
  abstract generate(transactions: Transaction[], loadConfig: LoadModelConfig): string;

  /**
   * Save generated script to file
   */
  public async generateAndSave(
    transactions: Transaction[],
    loadConfig: LoadModelConfig,
    filePath: string
  ): Promise<void> {
    const fs = await import('fs/promises');
    const content = this.generate(transactions, loadConfig);
    await fs.writeFile(filePath, content, 'utf-8');
  }

  /**
   * Format transaction name for the tool
   */
  protected formatTransactionName(name: string): string {
    return name.replace(/\s+/g, '_').toLowerCase();
  }

  /**
   * Escape special characters for the tool's format
   */
  protected escapeString(str: string): string {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/\t/g, '\\t');
  }

  /**
   * Format URL for the tool
   */
  protected formatURL(url: string): string {
    // Handle parameterized URLs
    if (url.includes('${')) {
      return url;
    }
    return url;
  }

  /**
   * Get milliseconds to seconds conversion
   */
  protected msToSeconds(ms: number): number {
    return Math.ceil(ms / 1000);
  }

  /**
   * Generate header for script file
   */
  protected generateHeader(): string {
    return `// Generated by PerfWeaver\n// ${new Date().toISOString()}\n\n`;
  }
}
